### ISSUE TITLE
[Enigma] Dynamic

### ISSUE THREAD

**Issue by pavel-b-novikov** [chinkypinky/nsudotnet#1]
Вы серьезно? Зачем вам dynamic?

**Comment by pavel-b-novikov** [comment]
То есть вы не смогли найти общего предка в иерархии наследования?

**Comment by chinkypinky** [comment]
Видимо, не углядел. Сейчас все поправлю.

**Comment by pavel-b-novikov** [comment]
И вот теперь у вас-таки не всё диспозится

**Comment by chinkypinky** [comment]
Надеюсь, что поправил нормально, а не как обычно.

**Comment by pavel-b-novikov** [comment]
Ну вы вручную просто развернули ```using```. Да ещё и криво. Ну еманэ

**Comment by chinkypinky** [comment]
Пофиксил, но говорят, что так не рекомендуется делать, хотя дальше нигде не используется alg.

**Comment by pavel-b-novikov** [comment]
Так не рекомендуется делать, если вы долбоеб. Но вы же не долбоеб, верно?
