### ISSUE TITLE
[LinesCounter] Строки

### ISSUE THREAD

**Issue by pavel-b-novikov** [chinkypinky/nsudotnet#5]
```csharp
new String(line
                   .Where(x => x != ' ' && x != '\r' && x != '\n')
                   .ToArray())
```

Серьезно штоле? То есть почти на каждую входную строку вы создаете ещё одну строку? До этого момента я думал что решения хуже чем regex нет. Ошибался.

**Comment by chinkypinky** [comment]
Я понимаю, что это не лучшее решение, но без новых строк, вроде как, не обойтись. Вы предлагаете посимвольно считывать? Просто даже если использовать Trim, то он тоже создает новую строку.

**Comment by pavel-b-novikov** [comment]
Слова "стейт-машина" вам говорят о чем-нибудь?

**Comment by chinkypinky** [comment]
Да,слышал. Но только в теории.

**Comment by chinkypinky** [comment]
Это, конечно, не стейт-машина, но без создания строк.

**Comment by pavel-b-novikov** [comment]
Ну что-то вроде того
